DROP TABLE IF EXISTS public.livecontrolsegment, public.livecontrolcommand, public.livecontrolsession, public.telemetryreading, public.rollbackrequest, public.jobhistory, public.workflowhistory, public.job, public.workflow, public.devicestatus, public.devicecapability, public.devicecredential, public.devicepermission, public.appusercredential, public.appuser, public.device, public.commandcatalogue, public.map CASCADE;

-- Refactored database schema for Minimal Nano Robocar + Legacy Grid Robot.
-- Drops existing project tables first, then recreates the schema.
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appuser; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appuser (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    displayname character varying(200) NOT NULL,
    role character varying(50) DEFAULT 'User'::character varying NOT NULL,
    isactive boolean DEFAULT true NOT NULL,
    lastloginatutc timestamp without time zone,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_appuser_role CHECK (((role)::text = ANY ((ARRAY['Admin'::character varying, 'User'::character varying])::text[])))
);


--
-- Name: appuser_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appusercredential; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appusercredential (
    id integer NOT NULL,
    appuserid integer NOT NULL,
    passwordhash character varying(1000) NOT NULL,
    passwordhashalgorithm character varying(100) DEFAULT 'PBKDF2_SHA256_V2'::character varying NOT NULL,
    passwordchangedatutc timestamp without time zone,
    mustresetpassword boolean DEFAULT false NOT NULL,
    failedlogincount integer DEFAULT 0 NOT NULL,
    lockedoutuntilutc timestamp without time zone,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_appusercredential_failedlogincount CHECK ((failedlogincount >= 0)),
    CONSTRAINT ck_appusercredential_hashalgorithm CHECK (((passwordhashalgorithm)::text = ANY ((ARRAY['PBKDF2_SHA256_V1'::character varying, 'PBKDF2_SHA256_V2'::character varying])::text[])))
);


--
-- Name: appusercredential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appusercredential ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appusercredential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commandcatalogue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commandcatalogue (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(1000),
    executionkind character varying(50) DEFAULT 'Mode'::character varying NOT NULL,
    rollbackkind character varying(50) DEFAULT 'None'::character varying NOT NULL,
    inversecommandname character varying(100),
    requiresduration boolean DEFAULT false NOT NULL,
    isactive boolean DEFAULT true NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_commandcatalogue_executionkind CHECK (((executionkind)::text = ANY ((ARRAY['Grid'::character varying, 'Continuous'::character varying, 'Mode'::character varying, 'Query'::character varying])::text[]))),
    CONSTRAINT ck_commandcatalogue_rollbackkind CHECK (((rollbackkind)::text = ANY ((ARRAY['Exact'::character varying, 'BestEffort'::character varying, 'None'::character varying])::text[]))),
    CONSTRAINT ck_commandcatalogue_inverse_required CHECK ((((rollbackkind)::text = 'None'::text AND inversecommandname IS NULL) OR ((rollbackkind)::text <> 'None'::text AND inversecommandname IS NOT NULL)))
);


--
-- Name: commandcatalogue_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commandcatalogue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commandcatalogue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    deviceidentifier character varying(100) NOT NULL,
    devicetype character varying(100) NOT NULL,
    mapid integer,
    description character varying(1000),
    isactive boolean DEFAULT true NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: device_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devicecapability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devicecapability (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    commandcatalogueid integer NOT NULL,
    requiresmap boolean DEFAULT false NOT NULL,
    description character varying(1000),
    isactive boolean DEFAULT true NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: devicecapability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devicecapability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devicecapability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devicecredential; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devicecredential (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    name character varying(200) NOT NULL,
    credentialidentifier character varying(100) NOT NULL,
    secretkeyprefix character varying(100) NOT NULL,
    secrethash character varying(500) NOT NULL,
    hashalgorithm character varying(100) DEFAULT 'HMACSHA256_V1'::character varying NOT NULL,
    expiresatutc timestamp without time zone,
    lastusedatutc timestamp without time zone,
    lastusedipaddress character varying(100),
    lastuseduseragent character varying(500),
    revokedatutc timestamp without time zone,
    revocationreason character varying(1000),
    isactive boolean DEFAULT true NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_devicecredential_hashalgorithm CHECK (((hashalgorithm)::text = ANY ((ARRAY['HMACSHA256_V1'::character varying, 'HMACSHA256'::character varying])::text[])))
);


--
-- Name: devicecredential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devicecredential ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devicecredential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devicepermission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devicepermission (
    id integer NOT NULL,
    appuserid integer NOT NULL,
    deviceid integer NOT NULL,
    permissionlevel character varying(50) DEFAULT 'Viewer'::character varying NOT NULL,
    isactive boolean DEFAULT true NOT NULL,
    expiresatutc timestamp without time zone,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_devicepermission_level CHECK (((permissionlevel)::text = ANY ((ARRAY['Viewer'::character varying, 'Operator'::character varying, 'Manager'::character varying, 'Owner'::character varying])::text[])))
);


--
-- Name: devicepermission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devicepermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devicepermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devicestatus; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devicestatus (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    connectionstate character varying(50) DEFAULT 'Unknown'::character varying NOT NULL,
    operationalstate character varying(50) DEFAULT 'Unknown'::character varying NOT NULL,
    lastseenatutc timestamp without time zone,
    lastheartbeatatutc timestamp without time zone,
    posemapid integer,
    gridx integer,
    gridy integer,
    facing character varying(50),
    isgridaligned boolean DEFAULT false NOT NULL,
    isgridposetrusted boolean DEFAULT false NOT NULL,
    poseconfidence double precision,
    estimatedxcm double precision,
    estimatedycm double precision,
    estimatedheadingdegrees double precision,
    isinsidemap boolean,
    statusmessage character varying(1000),
    lasterrorcode character varying(100),
    lasterrormessage character varying(1000),
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_devicestatus_connectionstate CHECK (((connectionstate)::text = ANY ((ARRAY['Unknown'::character varying, 'Online'::character varying, 'Offline'::character varying])::text[]))),
    CONSTRAINT ck_devicestatus_facing CHECK (((facing IS NULL) OR ((facing)::text = ANY ((ARRAY['North'::character varying, 'East'::character varying, 'South'::character varying, 'West'::character varying])::text[])))),
    CONSTRAINT ck_devicestatus_grid_pose_fields CHECK ((((gridx IS NULL) AND (gridy IS NULL) AND (facing IS NULL)) OR ((gridx IS NOT NULL) AND (gridy IS NOT NULL) AND (facing IS NOT NULL)))),
    CONSTRAINT ck_devicestatus_heading CHECK (((estimatedheadingdegrees IS NULL) OR ((estimatedheadingdegrees >= (0)::double precision) AND (estimatedheadingdegrees < (360)::double precision)))),
    CONSTRAINT ck_devicestatus_operationalstate CHECK (((operationalstate)::text = ANY ((ARRAY['Unknown'::character varying, 'Idle'::character varying, 'Executing'::character varying, 'Paused'::character varying, 'Stopped'::character varying, 'Faulted'::character varying])::text[]))),
    CONSTRAINT ck_devicestatus_poseconfidence CHECK (((poseconfidence IS NULL) OR ((poseconfidence >= (0)::double precision) AND (poseconfidence <= (1)::double precision))))
);


--
-- Name: devicestatus_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devicestatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devicestatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    workflowid integer,
    stepnumber integer,
    commandcatalogueid integer NOT NULL,
    payloadjson jsonb DEFAULT '{}'::jsonb NOT NULL,
    providertype character varying(50) DEFAULT 'Api'::character varying NOT NULL,
    status character varying(50) DEFAULT 'Queued'::character varying NOT NULL,
    requestedbyappuserid integer,
    claimedbydevicecredentialid integer,
    claimedatutc timestamp without time zone,
    leaseexpiresatutc timestamp without time zone,
    isrollback boolean DEFAULT false NOT NULL,
    rollbackofjobhistoryid integer,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_job_provider CHECK (((providertype)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[]))),
    CONSTRAINT ck_job_status CHECK (((status)::text = ANY ((ARRAY['Queued'::character varying, 'Claimed'::character varying, 'Executing'::character varying, 'Completed'::character varying, 'Failed'::character varying, 'Cancelled'::character varying, 'Expired'::character varying, 'RolledBack'::character varying])::text[]))),
    CONSTRAINT ck_job_stepnumber CHECK (((stepnumber IS NULL) OR (stepnumber > 0)))
);


--
-- Name: job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobhistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobhistory (
    id integer NOT NULL,
    jobid integer,
    workflowid integer,
    stepnumber integer,
    deviceid integer NOT NULL,
    commandcatalogueid integer,
    commandname character varying(100) NOT NULL,
    payloadjson jsonb DEFAULT '{}'::jsonb NOT NULL,
    providertype character varying(50) DEFAULT 'Api'::character varying NOT NULL,
    executionkind character varying(50) DEFAULT 'Mode'::character varying NOT NULL,
    rollbackkind character varying(50) DEFAULT 'None'::character varying NOT NULL,
    executed boolean NOT NULL,
    success boolean NOT NULL,
    resultjson jsonb,
    failurecode character varying(100),
    failuremessage character varying(1000),
    startedatutc timestamp without time zone,
    completedatutc timestamp without time zone,
    durationms integer,
    rollbackofjobhistoryid integer,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_jobhistory_provider CHECK (((providertype)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[]))),
    CONSTRAINT ck_jobhistory_executionkind CHECK (((executionkind)::text = ANY ((ARRAY['Grid'::character varying, 'Continuous'::character varying, 'Mode'::character varying, 'Query'::character varying])::text[]))),
    CONSTRAINT ck_jobhistory_rollbackkind CHECK (((rollbackkind)::text = ANY ((ARRAY['Exact'::character varying, 'BestEffort'::character varying, 'None'::character varying])::text[]))),
    CONSTRAINT ck_jobhistory_durationms CHECK (((durationms IS NULL) OR (durationms >= 0))),
    CONSTRAINT ck_jobhistory_stepnumber CHECK (((stepnumber IS NULL) OR (stepnumber > 0)))
);


--
-- Name: jobhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: map; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.map (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    columns integer NOT NULL,
    rows integer NOT NULL,
    cellsizecm double precision NOT NULL,
    description character varying(1000),
    isactive boolean DEFAULT true NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_map_cellsizecm CHECK ((cellsizecm >= (10)::double precision)),
    CONSTRAINT ck_map_columns CHECK ((columns > 0)),
    CONSTRAINT ck_map_rows CHECK ((rows > 0))
);


--
-- Name: map_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rollbackrequest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rollbackrequest (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    requestedbyappuserid integer,
    requestedbyprovider character varying(50) DEFAULT 'Api'::character varying NOT NULL,
    targettype character varying(50) NOT NULL,
    targetidsjson jsonb DEFAULT '[]'::jsonb NOT NULL,
    status character varying(50) DEFAULT 'Requested'::character varying NOT NULL,
    generatedworkflowid integer,
    generatedjobid integer,
    failurecode character varying(100),
    failuremessage character varying(1000),
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_rollbackrequest_one_generated_target CHECK (((generatedworkflowid IS NULL) OR (generatedjobid IS NULL))),
    CONSTRAINT ck_rollbackrequest_provider CHECK (((requestedbyprovider)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[]))),
    CONSTRAINT ck_rollbackrequest_status CHECK (((status)::text = ANY ((ARRAY['Requested'::character varying, 'Generated'::character varying, 'Failed'::character varying, 'Cancelled'::character varying, 'DuplicateRejected'::character varying])::text[]))),
    CONSTRAINT ck_rollbackrequest_targettype CHECK (((targettype)::text = ANY ((ARRAY['JobHistory'::character varying, 'WorkflowHistory'::character varying])::text[])))
);


--
-- Name: rollbackrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rollbackrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rollbackrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--


--
-- Name: livecontrolsession; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livecontrolsession (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    appuserid integer NOT NULL,
    status character varying(50) DEFAULT 'Active'::character varying NOT NULL,
    stopreason character varying(100),
    isrollback boolean DEFAULT false NOT NULL,
    rollbackoflivecontrolsessionid integer,
    startedatutc timestamp without time zone NOT NULL,
    endedatutc timestamp without time zone,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_livecontrolsession_status CHECK (((status)::text = ANY ((ARRAY['Active'::character varying, 'Completed'::character varying, 'Cancelled'::character varying, 'Failed'::character varying, 'Expired'::character varying])::text[]))),
    CONSTRAINT ck_livecontrolsession_stopreason CHECK (((stopreason IS NULL) OR ((stopreason)::text = ANY ((ARRAY['UserReleased'::character varying, 'Timeout'::character varying, 'RainOverride'::character varying, 'ManualStop'::character varying, 'NewSessionStarted'::character varying, 'Cancelled'::character varying])::text[]))))
);


--
-- Name: livecontrolsession_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.livecontrolsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livecontrolsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livecontrolcommand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livecontrolcommand (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    appuserid integer,
    livecontrolsessionid integer,
    commandname character varying(100) NOT NULL,
    payloadjson jsonb DEFAULT '{}'::jsonb NOT NULL,
    sequencenumber integer DEFAULT 0 NOT NULL,
    expiresatutc timestamp without time zone NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_livecontrolcommand_name CHECK (((commandname)::text = ANY ((ARRAY['MOVE_FORWARD'::character varying, 'MOVE_BACKWARD'::character varying, 'ROTATE_LEFT'::character varying, 'ROTATE_RIGHT'::character varying, 'STOP'::character varying])::text[])))
);


--
-- Name: livecontrolcommand_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.livecontrolcommand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livecontrolcommand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livecontrolsegment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livecontrolsegment (
    id integer NOT NULL,
    livecontrolsessionid integer NOT NULL,
    commandname character varying(100) NOT NULL,
    payloadjson jsonb DEFAULT '{}'::jsonb NOT NULL,
    durationms integer NOT NULL,
    success boolean DEFAULT true NOT NULL,
    failurecode character varying(100),
    failuremessage character varying(1000),
    startedatutc timestamp without time zone NOT NULL,
    completedatutc timestamp without time zone NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_livecontrolsegment_commandname CHECK (((commandname)::text = ANY ((ARRAY['MOVE_FORWARD'::character varying, 'MOVE_BACKWARD'::character varying, 'ROTATE_LEFT'::character varying, 'ROTATE_RIGHT'::character varying, 'STOP'::character varying])::text[]))),
    CONSTRAINT ck_livecontrolsegment_durationms CHECK ((durationms >= 0))
);


--
-- Name: livecontrolsegment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.livecontrolsegment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livecontrolsegment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: telemetryreading; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telemetryreading (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    payloadjson jsonb DEFAULT '{}'::jsonb NOT NULL,
    providertype character varying(50) DEFAULT 'Poll'::character varying NOT NULL,
    recordedatutc timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_telemetryreading_provider CHECK (((providertype)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[])))
);


--
-- Name: telemetryreading_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telemetryreading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telemetryreading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow (
    id integer NOT NULL,
    deviceid integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    schemaversion character varying(50) DEFAULT '1.0'::character varying NOT NULL,
    executionmode character varying(50) DEFAULT 'BestEffort'::character varying NOT NULL,
    providertype character varying(50) DEFAULT 'Api'::character varying NOT NULL,
    status character varying(50) DEFAULT 'Queued'::character varying NOT NULL,
    requestedbyappuserid integer,
    claimedbydevicecredentialid integer,
    claimedatutc timestamp without time zone,
    leaseexpiresatutc timestamp without time zone,
    isrollback boolean DEFAULT false NOT NULL,
    rollbackofworkflowhistoryid integer,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    modifieddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_workflow_executionmode CHECK (((executionmode)::text = ANY ((ARRAY['BestEffort'::character varying, 'AllOrNothing'::character varying])::text[]))),
    CONSTRAINT ck_workflow_provider CHECK (((providertype)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[]))),
    CONSTRAINT ck_workflow_status CHECK (((status)::text = ANY ((ARRAY['Queued'::character varying, 'Claimed'::character varying, 'Executing'::character varying, 'Completed'::character varying, 'Failed'::character varying, 'Cancelled'::character varying, 'Expired'::character varying, 'RolledBack'::character varying])::text[])))
);


--
-- Name: workflow_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflowhistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflowhistory (
    id integer NOT NULL,
    workflowid integer,
    deviceid integer NOT NULL,
    providertype character varying(50) DEFAULT 'Api'::character varying NOT NULL,
    status character varying(50) DEFAULT 'Completed'::character varying NOT NULL,
    executed boolean NOT NULL,
    success boolean NOT NULL,
    startedatutc timestamp without time zone,
    completedatutc timestamp without time zone,
    failedstepnumber integer,
    failuremessage character varying(1000),
    rollbackofworkflowhistoryid integer,
    createddate timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT ck_workflowhistory_failedstep CHECK (((failedstepnumber IS NULL) OR (failedstepnumber > 0))),
    CONSTRAINT ck_workflowhistory_provider CHECK (((providertype)::text = ANY ((ARRAY['Api'::character varying, 'Console'::character varying, 'File'::character varying, 'Poll'::character varying, 'Rollback'::character varying])::text[]))),
    CONSTRAINT ck_workflowhistory_status CHECK (((status)::text = ANY ((ARRAY['Queued'::character varying, 'Claimed'::character varying, 'Executing'::character varying, 'Completed'::character varying, 'Failed'::character varying, 'Cancelled'::character varying, 'Expired'::character varying, 'RolledBack'::character varying])::text[])))
);


--
-- Name: workflowhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflowhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflowhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appuser appuser_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appuser
    ADD CONSTRAINT appuser_pkey PRIMARY KEY (id);


--
-- Name: appusercredential appusercredential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appusercredential
    ADD CONSTRAINT appusercredential_pkey PRIMARY KEY (id);


--
-- Name: commandcatalogue commandcatalogue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commandcatalogue
    ADD CONSTRAINT commandcatalogue_pkey PRIMARY KEY (id);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);


--
-- Name: devicecapability devicecapability_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicecapability
    ADD CONSTRAINT devicecapability_pkey PRIMARY KEY (id);


--
-- Name: devicecredential devicecredential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicecredential
    ADD CONSTRAINT devicecredential_pkey PRIMARY KEY (id);


--
-- Name: devicepermission devicepermission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicepermission
    ADD CONSTRAINT devicepermission_pkey PRIMARY KEY (id);


--
-- Name: devicestatus devicestatus_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicestatus
    ADD CONSTRAINT devicestatus_pkey PRIMARY KEY (id);


--
-- Name: job job_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);


--
-- Name: jobhistory jobhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_pkey PRIMARY KEY (id);


--


--
-- Name: livecontrolsession livecontrolsession_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsession
    ADD CONSTRAINT livecontrolsession_pkey PRIMARY KEY (id);


--
-- Name: livecontrolcommand livecontrolcommand_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolcommand
    ADD CONSTRAINT livecontrolcommand_pkey PRIMARY KEY (id);


--
-- Name: livecontrolsegment livecontrolsegment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsegment
    ADD CONSTRAINT livecontrolsegment_pkey PRIMARY KEY (id);

-- Name: map map_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.map
    ADD CONSTRAINT map_pkey PRIMARY KEY (id);


--
-- Name: rollbackrequest rollbackrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rollbackrequest
    ADD CONSTRAINT rollbackrequest_pkey PRIMARY KEY (id);


--
-- Name: telemetryreading telemetryreading_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetryreading
    ADD CONSTRAINT telemetryreading_pkey PRIMARY KEY (id);


--
-- Name: workflow workflow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (id);


--
-- Name: workflowhistory workflowhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflowhistory
    ADD CONSTRAINT workflowhistory_pkey PRIMARY KEY (id);


--
-- Name: ix_device_mapid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_device_mapid ON public.device USING btree (mapid);


--
-- Name: ix_devicecapability_commandcatalogueid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_devicecapability_commandcatalogueid ON public.devicecapability USING btree (commandcatalogueid);


--
-- Name: ix_devicecredential_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_devicecredential_deviceid ON public.devicecredential USING btree (deviceid);


--
-- Name: ix_devicepermission_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_devicepermission_deviceid ON public.devicepermission USING btree (deviceid);


--
-- Name: ix_devicestatus_posemapid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_devicestatus_posemapid ON public.devicestatus USING btree (posemapid);


--
-- Name: ix_job_claimedbydevicecredentialid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_claimedbydevicecredentialid ON public.job USING btree (claimedbydevicecredentialid);


--
-- Name: ix_job_commandcatalogueid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_commandcatalogueid ON public.job USING btree (commandcatalogueid);


--
-- Name: ix_job_device_status_createddate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_device_status_createddate ON public.job USING btree (deviceid, status, createddate);


--
-- Name: ix_job_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_deviceid ON public.job USING btree (deviceid);


--
-- Name: ix_job_requestedbyappuserid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_requestedbyappuserid ON public.job USING btree (requestedbyappuserid);


--
-- Name: ix_job_rollbackofjobhistoryid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_rollbackofjobhistoryid ON public.job USING btree (rollbackofjobhistoryid);


--
-- Name: ix_job_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_status ON public.job USING btree (status);


--
-- Name: ix_job_workflowid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_job_workflowid ON public.job USING btree (workflowid);


--
-- Name: ix_jobhistory_commandcatalogueid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_commandcatalogueid ON public.jobhistory USING btree (commandcatalogueid);


--
-- Name: ix_jobhistory_device_createddate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_device_createddate ON public.jobhistory USING btree (deviceid, createddate);


--
-- Name: ix_jobhistory_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_deviceid ON public.jobhistory USING btree (deviceid);


--
-- Name: ix_jobhistory_jobid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_jobid ON public.jobhistory USING btree (jobid);


--
-- Name: ix_jobhistory_rollbackofjobhistoryid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_rollbackofjobhistoryid ON public.jobhistory USING btree (rollbackofjobhistoryid);


--
-- Name: ix_jobhistory_workflowid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_jobhistory_workflowid ON public.jobhistory USING btree (workflowid);


--


--
-- Name: ix_livecontrolsession_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_livecontrolsession_deviceid ON public.livecontrolsession USING btree (deviceid);


--
-- Name: ix_livecontrolsession_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_livecontrolsession_status ON public.livecontrolsession USING btree (status);


--
-- Name: ix_livecontrolcommand_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_livecontrolcommand_deviceid ON public.livecontrolcommand USING btree (deviceid);


--
-- Name: ix_livecontrolcommand_sessionid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_livecontrolcommand_sessionid ON public.livecontrolcommand USING btree (livecontrolsessionid);


--
-- Name: ix_livecontrolsegment_sessionid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_livecontrolsegment_sessionid ON public.livecontrolsegment USING btree (livecontrolsessionid);

-- Name: ix_rollbackrequest_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_rollbackrequest_deviceid ON public.rollbackrequest USING btree (deviceid);


--
-- Name: ix_rollbackrequest_generatedjobid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_rollbackrequest_generatedjobid ON public.rollbackrequest USING btree (generatedjobid);


--
-- Name: ix_rollbackrequest_generatedworkflowid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_rollbackrequest_generatedworkflowid ON public.rollbackrequest USING btree (generatedworkflowid);


--
-- Name: ix_rollbackrequest_requestedbyappuserid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_rollbackrequest_requestedbyappuserid ON public.rollbackrequest USING btree (requestedbyappuserid);


--
-- Name: ix_rollbackrequest_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_rollbackrequest_status ON public.rollbackrequest USING btree (status);


--
-- Name: ix_telemetryreading_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_telemetryreading_deviceid ON public.telemetryreading USING btree (deviceid);


--
-- Name: ix_telemetryreading_deviceid_recordedatutc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_telemetryreading_deviceid_recordedatutc ON public.telemetryreading USING btree (deviceid, recordedatutc DESC);


--
-- Name: ix_workflow_claimedbydevicecredentialid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflow_claimedbydevicecredentialid ON public.workflow USING btree (claimedbydevicecredentialid);


--
-- Name: ix_workflow_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflow_deviceid ON public.workflow USING btree (deviceid);


--
-- Name: ix_workflow_requestedbyappuserid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflow_requestedbyappuserid ON public.workflow USING btree (requestedbyappuserid);


--
-- Name: ix_workflow_rollbackofworkflowhistoryid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflow_rollbackofworkflowhistoryid ON public.workflow USING btree (rollbackofworkflowhistoryid);


--
-- Name: ix_workflow_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflow_status ON public.workflow USING btree (status);


--
-- Name: ix_workflowhistory_device_createddate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflowhistory_device_createddate ON public.workflowhistory USING btree (deviceid, createddate);


--
-- Name: ix_workflowhistory_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflowhistory_deviceid ON public.workflowhistory USING btree (deviceid);


--
-- Name: ix_workflowhistory_rollbackofworkflowhistoryid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflowhistory_rollbackofworkflowhistoryid ON public.workflowhistory USING btree (rollbackofworkflowhistoryid);


--
-- Name: ix_workflowhistory_workflowid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workflowhistory_workflowid ON public.workflowhistory USING btree (workflowid);


--
-- Name: ux_appuser_email_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_appuser_email_lower ON public.appuser USING btree (lower((email)::text));


--
-- Name: ux_appusercredential_appuserid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_appusercredential_appuserid ON public.appusercredential USING btree (appuserid);


--
-- Name: ux_commandcatalogue_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_commandcatalogue_name_lower ON public.commandcatalogue USING btree (lower((name)::text));


--
-- Name: ux_device_identifier_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_device_identifier_lower ON public.device USING btree (lower((deviceidentifier)::text));


--
-- Name: ux_devicecapability_device_command; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_devicecapability_device_command ON public.devicecapability USING btree (deviceid, commandcatalogueid);


--
-- Name: ux_devicecredential_identifier_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_devicecredential_identifier_lower ON public.devicecredential USING btree (lower((credentialidentifier)::text));


--
-- Name: ux_devicepermission_user_device; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_devicepermission_user_device ON public.devicepermission USING btree (appuserid, deviceid);


--
-- Name: ux_devicestatus_deviceid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_devicestatus_deviceid ON public.devicestatus USING btree (deviceid);


--
-- Name: ux_map_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_map_name_lower ON public.map USING btree (lower((name)::text));


--
-- Name: appusercredential appusercredential_appuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appusercredential
    ADD CONSTRAINT appusercredential_appuserid_fkey FOREIGN KEY (appuserid) REFERENCES public.appuser(id) ON DELETE CASCADE;


--
-- Name: device device_mapid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_mapid_fkey FOREIGN KEY (mapid) REFERENCES public.map(id) ON DELETE SET NULL;


--
-- Name: devicecapability devicecapability_commandcatalogueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicecapability
    ADD CONSTRAINT devicecapability_commandcatalogueid_fkey FOREIGN KEY (commandcatalogueid) REFERENCES public.commandcatalogue(id) ON DELETE RESTRICT;


--
-- Name: devicecapability devicecapability_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicecapability
    ADD CONSTRAINT devicecapability_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE CASCADE;


--
-- Name: devicecredential devicecredential_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicecredential
    ADD CONSTRAINT devicecredential_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE CASCADE;


--
-- Name: devicepermission devicepermission_appuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicepermission
    ADD CONSTRAINT devicepermission_appuserid_fkey FOREIGN KEY (appuserid) REFERENCES public.appuser(id) ON DELETE CASCADE;


--
-- Name: devicepermission devicepermission_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicepermission
    ADD CONSTRAINT devicepermission_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE CASCADE;


--
-- Name: devicestatus devicestatus_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicestatus
    ADD CONSTRAINT devicestatus_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE CASCADE;


--
-- Name: devicestatus devicestatus_posemapid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devicestatus
    ADD CONSTRAINT devicestatus_posemapid_fkey FOREIGN KEY (posemapid) REFERENCES public.map(id) ON DELETE SET NULL;


--
-- Name: job fk_job_rollbackofjobhistoryid; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT fk_job_rollbackofjobhistoryid FOREIGN KEY (rollbackofjobhistoryid) REFERENCES public.jobhistory(id) ON DELETE SET NULL;


--
-- Name: workflow fk_workflow_rollbackofworkflowhistoryid; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT fk_workflow_rollbackofworkflowhistoryid FOREIGN KEY (rollbackofworkflowhistoryid) REFERENCES public.workflowhistory(id) ON DELETE SET NULL;


--
-- Name: job job_claimedbydevicecredentialid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_claimedbydevicecredentialid_fkey FOREIGN KEY (claimedbydevicecredentialid) REFERENCES public.devicecredential(id) ON DELETE SET NULL;


--
-- Name: job job_commandcatalogueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_commandcatalogueid_fkey FOREIGN KEY (commandcatalogueid) REFERENCES public.commandcatalogue(id) ON DELETE RESTRICT;


--
-- Name: job job_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: job job_requestedbyappuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_requestedbyappuserid_fkey FOREIGN KEY (requestedbyappuserid) REFERENCES public.appuser(id) ON DELETE SET NULL;


--
-- Name: job job_workflowid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_workflowid_fkey FOREIGN KEY (workflowid) REFERENCES public.workflow(id) ON DELETE CASCADE;


--
-- Name: jobhistory jobhistory_commandcatalogueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_commandcatalogueid_fkey FOREIGN KEY (commandcatalogueid) REFERENCES public.commandcatalogue(id) ON DELETE SET NULL;


--
-- Name: jobhistory jobhistory_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: jobhistory jobhistory_jobid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_jobid_fkey FOREIGN KEY (jobid) REFERENCES public.job(id) ON DELETE SET NULL;


--
-- Name: jobhistory jobhistory_rollbackofjobhistoryid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_rollbackofjobhistoryid_fkey FOREIGN KEY (rollbackofjobhistoryid) REFERENCES public.jobhistory(id) ON DELETE SET NULL;


--
-- Name: jobhistory jobhistory_workflowid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobhistory
    ADD CONSTRAINT jobhistory_workflowid_fkey FOREIGN KEY (workflowid) REFERENCES public.workflow(id) ON DELETE SET NULL;


--
-- Name: rollbackrequest rollbackrequest_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rollbackrequest
    ADD CONSTRAINT rollbackrequest_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: rollbackrequest rollbackrequest_generatedjobid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rollbackrequest
    ADD CONSTRAINT rollbackrequest_generatedjobid_fkey FOREIGN KEY (generatedjobid) REFERENCES public.job(id) ON DELETE SET NULL;


--
-- Name: rollbackrequest rollbackrequest_generatedworkflowid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rollbackrequest
    ADD CONSTRAINT rollbackrequest_generatedworkflowid_fkey FOREIGN KEY (generatedworkflowid) REFERENCES public.workflow(id) ON DELETE SET NULL;


--
-- Name: rollbackrequest rollbackrequest_requestedbyappuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rollbackrequest
    ADD CONSTRAINT rollbackrequest_requestedbyappuserid_fkey FOREIGN KEY (requestedbyappuserid) REFERENCES public.appuser(id) ON DELETE SET NULL;


--
-- Name: telemetryreading telemetryreading_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetryreading
    ADD CONSTRAINT telemetryreading_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE CASCADE;


--
-- Name: workflow workflow_claimedbydevicecredentialid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_claimedbydevicecredentialid_fkey FOREIGN KEY (claimedbydevicecredentialid) REFERENCES public.devicecredential(id) ON DELETE SET NULL;


--
-- Name: workflow workflow_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: workflow workflow_requestedbyappuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_requestedbyappuserid_fkey FOREIGN KEY (requestedbyappuserid) REFERENCES public.appuser(id) ON DELETE SET NULL;


--
-- Name: workflowhistory workflowhistory_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflowhistory
    ADD CONSTRAINT workflowhistory_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: workflowhistory workflowhistory_rollbackofworkflowhistoryid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflowhistory
    ADD CONSTRAINT workflowhistory_rollbackofworkflowhistoryid_fkey FOREIGN KEY (rollbackofworkflowhistoryid) REFERENCES public.workflowhistory(id) ON DELETE SET NULL;


--
-- Name: workflowhistory workflowhistory_workflowid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflowhistory
    ADD CONSTRAINT workflowhistory_workflowid_fkey FOREIGN KEY (workflowid) REFERENCES public.workflow(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--



--
-- Name: livecontrolsession livecontrolsession_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsession
    ADD CONSTRAINT livecontrolsession_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: livecontrolsession livecontrolsession_appuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsession
    ADD CONSTRAINT livecontrolsession_appuserid_fkey FOREIGN KEY (appuserid) REFERENCES public.appuser(id) ON DELETE RESTRICT;


--
-- Name: livecontrolsession livecontrolsession_rollbackof_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsession
    ADD CONSTRAINT livecontrolsession_rollbackof_fkey FOREIGN KEY (rollbackoflivecontrolsessionid) REFERENCES public.livecontrolsession(id) ON DELETE SET NULL;


--
-- Name: livecontrolcommand livecontrolcommand_deviceid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolcommand
    ADD CONSTRAINT livecontrolcommand_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES public.device(id) ON DELETE RESTRICT;


--
-- Name: livecontrolcommand livecontrolcommand_appuserid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolcommand
    ADD CONSTRAINT livecontrolcommand_appuserid_fkey FOREIGN KEY (appuserid) REFERENCES public.appuser(id) ON DELETE SET NULL;


--
-- Name: livecontrolcommand livecontrolcommand_sessionid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolcommand
    ADD CONSTRAINT livecontrolcommand_sessionid_fkey FOREIGN KEY (livecontrolsessionid) REFERENCES public.livecontrolsession(id) ON DELETE SET NULL;


--
-- Name: livecontrolsegment livecontrolsegment_sessionid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livecontrolsegment
    ADD CONSTRAINT livecontrolsegment_sessionid_fkey FOREIGN KEY (livecontrolsessionid) REFERENCES public.livecontrolsession(id) ON DELETE CASCADE;
